apiVersion: v1
kind: Service
metadata:
  name: podinfo-lb
spec:
  selector:
    app: podinfo
  ports:
  - name: http
    protocol: TCP
    port: 80
    targetPort: 9898
  - name: grpc
    protocol: TCP
    port: 443
    targetPort: 9999
  type: LoadBalancer
